services:
  #db:
    #image: postgres
    #container_name: mysite-dev-db
    #restart: unless-stopped
    #environment:
      #- POSTGRES_USER=adams
      #- POSTGRES_PASSWORD=adams
      #- POSTGRES_HOST=localhost
      #- POSTGRES_PORT=5432
      #- POSTGRES_DB=adams
    #volumes:
     #- pg_data:/var/lib/postgresql/data/
    #ports:
     #- 5432:5432

  app:
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
      target: production
    image: mysite-prod-image
    container_name: mysite-prod-app
    volumes:
      - ./mysite/:/home/app/code/
    ports:
      - 8000:8000
    env_file:
      - .env
    #depends_on:
    #  - db

#volumes:
  #pg_data: